---
- hosts: all 
  become: yes

  tasks:
  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600

  - name: Ensure sudo group exists
    group: 
      name: sudo 
      state: present

  - name: Add ubuntu user and add it to sudo
    user: 
      name: ubuntu
      state: present
      createhome: yes
    become: yes
    become_method: "sudo"

  - name: Set up authorized keys for the ubuntu user
    authorized_key: 
      user: ubuntu 
      key: "{{item}}"
    with_file:
      - ~/id_rsa.pub

  - name: Add ubuntu users to sudoers
    template:
      src: templates/sudoers.j2
      dest: /etc/sudoers.d/ubuntu
      validate: 'visudo -cf %s'
      mode: 0440
    
  - name: Install packages
    apt:
      name:
        - python3-pip 
        - apt-transport-https 
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: present

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: 
      update_cache: yes 
      name: docker-ce
      state: latest

  - name: Install Docker Module for Python
    pip:
      name: docker-py