---
- hosts: k8s-masters, k8s-workers
  become: true

  tasks:
    - name: Add Google's Official GPG Key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes Repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main 
        state: present
        filename: kubernetes
        mode: 0600

    - name: Installing Kubernetes Cluster Packages
      apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: present
   
    - name: Enable kubelet service
      service:
        name: kubelet
        enabled: yes

    - name: Reboot all nodes
      reboot:
        post_reboot_delay: 10
        reboot_timeout: 40
        connect_timeout: 60
        test_command: uptime